# Generated by Django 2.0.3 on 2018-04-02 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('slika', models.CharField(max_length=1000)),
                ('opis', models.CharField(max_length=10000)),
                ('nacin_pripreme', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Kategorije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sastojci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SastojciUJelu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jelo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepti.Jela')),
                ('sastojak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepti.Sastojci')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='jela',
            name='kategorija_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepti.Kategorije'),
        ),
    ]
