# Generated by Django 2.0.3 on 2018-04-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0002_auto_20180403_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='jela',
            name='svidja_mi_se',
            field=models.BooleanField(default=False),
        ),
    ]
