# Generated by Django 2.0.3 on 2018-04-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0004_auto_20180404_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jela',
            name='opis',
            field=models.TextField(),
        ),
    ]
