# Generated by Django 2.0.3 on 2018-04-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0005_auto_20180404_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jela',
            name='svidja_mi_se',
        ),
    ]
