# Generated by Django 2.0.3 on 2018-04-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0008_auto_20180406_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jela',
            name='kategorija',
        ),
        migrations.AddField(
            model_name='jela',
            name='kategorija',
            field=models.ManyToManyField(to='recepti.Kategorije'),
        ),
    ]
