# Generated by Django 2.0.3 on 2018-04-16 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0010_auto_20180417_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jela',
            name='kategorija',
        ),
        migrations.AddField(
            model_name='jela',
            name='kategorija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recepti.Kategorije'),
        ),
        migrations.RemoveField(
            model_name='jela',
            name='sastojci',
        ),
        migrations.AddField(
            model_name='jela',
            name='sastojci',
            field=models.ManyToManyField(to='recepti.Sastojci'),
        ),
    ]
